### ISSUE TITLE
Swift 5.1

### ISSUE THREAD

**Issue by ralomue01** [airbnb/lottie-ios#1021]
When we will have support for Swift 5.1?

**Comment by jrtb** [comment]
bump

**Comment by iBolom** [comment]
I still get this error: "Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler".

**Comment by jrtb** [comment]
Same 👆

**Comment by WyattMufson** [comment]
@buba447 Any idea when 5.1 support will be added?

**Comment by iBolom** [comment]
I managed to solve the issue with next steps:
1. Clone lottie-ios project locally.
2. Run the project in Xcode 11, it will generate .framework file.
3. Manually import .framework file in the desire project.

That's should be it, because i don't use cocoapods and carthage for Lottie, i manually import this framework into project but first step must be building with Xcode 11.

**Comment by jrtb** [comment]
For others if you're using Carthage, make sure you run `carthage update` once you upgrade to Xcode 11. That should rebuild the framework with Swift 5.1.

**Comment by udayasri** [comment]
When I try to compile the lottie with the Xcode 11 using carthage update , it gives me this error 
`Dependency "lottie-ios" has no shared framework schemes`

**Comment by buba447** [comment]
Fixed!
