### ISSUE TITLE
Unable to use Lottie with MacOS app

### ISSUE THREAD

**Issue by staticdreams** [airbnb/lottie-ios#1057]
## Lottie-iOS Issue
Unable to use Lottie for an macOS app. I'm using latest **macOS Catalina** + **Xcode 11.1**
I'm trying to use it with a **SwiftUI** app (if that helps)

Please make it compatible latest Xcode / macOS version

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [x] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.3

## What Platform are you on? 

- [x] MacOS
- [ ] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 
Compiles without errors

## Actual Behavior
There are no issues installing the library, but unable to compile, saying ``ld: framework not found Lottie``. I tried installing using **Package Manager** method and **Cocoa Pods** method. Neither works.

<img width="872" alt="Screenshot 2019-10-11 at 09 05 29" src="https://user-images.githubusercontent.com/988705/66631365-4bf7ca00-ec06-11e9-9bd3-76c9ecdbcac0.png">

**_BTW installing and compiling for iOS app yields no errors or warnings._**

## How to reproduce

- Create new project -> macOS -> App
- Add the Lottie library using preferred method (e.g Package Manager)
- Hit Run (Command +R)

## Animation JSON
Unable to make it work. Not at the animation step yet.

**Comment by buba447** [comment]
Did you try deleting derived data? Are you still experiencing this issue?

**Comment by buba447** [comment]
Ohhh Are you using swift package manager? It hasnt been setup to work with macos yet. You can, however manually add the library or use something like cocoapods or carthage.

**Comment by buba447** [comment]
Swift Package Manager does not allow targets with overlapping sources. Lottie is structured to share as many resources as it can between iOS and MacOS, with only a few platform specific files. This project structure does not work with the way swift package manager expects packages. 

In order to support macos in SPM the project needs to be restructured. 

For now there is a workaround, set the `Branch` field to `lottie/macos-spm`
Read more here https://github.com/airbnb/lottie-ios#adding-it-to-an-existent-ios-project-via-swift-package-manager

**Comment by calda** [comment]
Should be fixed by #1428, which added macOS support to `Package.swift` on `master`. Thanks for filing this issue!
