### ISSUE TITLE
Could not find module 'Lottie' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator on macbook m1

### ISSUE THREAD

**Issue by davamp** [airbnb/lottie-ios#1293]

**Comment by silentgco** [comment]
Same issue

**Comment by muukii** [comment]
How do you building? using Carthage or something?

**Comment by davamp** [comment]
> How do you building? using Carthage or something?

No, I'm using Cocoapod

**Comment by muukii** [comment]
@davamp 
thanks, something went wrong, you will be able to compile arm64 for the simulator.
It might be caused by other library something prebuilt.
You probably need to investigate all of the dependencies that can be build as arm64. otherwise, you need to fix using x86_64 for the simulator.

Did you see the link below? it would be helpful for you.
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by dev299** [comment]
I am also having the same issue with new M1 Mac. AFAIK, iPhone simulators are available in either arm64 or x86_64 architectures. 

In some cases, subset of users have to opt out of arm64 architecture due to library [linking issue](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios) with M1 Mac (and also for old Intel Macs).

In those cases, when arm64 are excluded, Xcode will attempt to run project in x86_64, but because lottie-ios does not seem to support x86_64 simulators for some reason, it will fail.

`Could not find module 'Lottie' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator`

I am also curious to know if there is any particular reason why this library can't run in simulator with x86_64 architecture. Can this restriction simply be relaxed with a simple config change?

**Comment by viktor-idenfy** [comment]
Any updates?

**Comment by claybridges** [comment]
I had luck with this changing the configuration away from Debug. I suspect it has something to do with this:

<img width="1340" alt="Screen Shot 2021-05-19 at 5 59 23 AM" src="https://user-images.githubusercontent.com/96004/118801026-8f98c800-b86e-11eb-8fbb-f7d24574fcbb.png">

However, lottie-ios is no different than any number of other pods in this one setting.

**Comment by gevartosky** [comment]
Hi, I'm having the same issue
Could not find module 'Lottie' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator.

Can't build on simulator or use swiftui previews :( 
I tried all the combinations I could find on VALID_ARCHS, Build Active Architecture Only, Excluded Architectures and such.

:(

**Comment by RamblinWreck77** [comment]
@gevartosky I don't think this issue is fixable user-side if you use SPM. @buba447 likely needs to re-release with "build active architecture only" set to "No" for both Debug & Release. If you are using a legacy cocoapods installation you can override this setting, otherwise I've found no way so far to fix it.

**Comment by RamblinWreck77** [comment]
To provide some clarity on reproducing this issue, I happens for me 100% of the time when you:

1) Use apple Silicion/M1

2) Xcode 12.5

3) Add lottie via SPM

4) import Lottie _anywhere_ in your project

5) Attempt to use SwiftUI previews.

Make a trivial VStack { Text("hello workd") } etc and the preview will fail to render with the error:

```
Could not find module 'Lottie' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator
```

**Comment by RamblinWreck77** [comment]
Hello all! I'm happy to report after some experimentation I _appear_ to have solved it.

Some caveats:

1) I'm on apple silicon

2) I'm only deploying to iOS and have it set to iOS13 and above (But I suspect iOS minimums of 11 and higher are ok to do this as well)

The fix:

-Go to project/build settings (so it applies to all targets)

-Search "arch" and get "Architectures". The default for debug/release is "standard architectures" which includes arm64 AND armv7

-Change the top/all values to "arm64". Clean build. 

-SwiftUI previews should work! I also have "build active architecture only" set to YES for debug, but that shouldn't matter anymore since we only support one arch.

What I think is happening:

-armv7 is old 32-bit iOS devices, the last of which that was sold is the 5C (!!!) For some reason, xcode 12.5 with a 13.0+ deployment target _still_ includes 32-bit armv7 as a supported architecture! I have no idea why this is the case. Removing it seemed to fix the problem.

**Comment by ghasemikasra39** [comment]
I am getting the same error on non-m1 chip

**Comment by ghasemikasra39** [comment]
> Hello all! I'm happy to report after some experimentation I _appear_ to have solved it.
> 
> Some caveats:
> 
> 1. I'm on apple silicon
> 2. I'm only deploying to iOS and have it set to iOS13 and above (But I suspect iOS minimums of 11 and higher are ok to do this as well)
> 
> The fix:
> 
> -Go to project/build settings (so it applies to all targets)
> 
> -Search "arch" and get "Architectures". The default for debug/release is "standard architectures" which includes arm64 AND armv7
> 
> -Change the top/all values to "arm64". Clean build.
> 
> -SwiftUI previews should work! I also have "build active architecture only" set to YES for debug, but that shouldn't matter anymore since we only support one arch.
> 
> What I think is happening:
> 
> -armv7 is old 32-bit iOS devices, the last of which that was sold is the 5C (!!!) For some reason, xcode 12.5 with a 13.0+ deployment target _still_ includes 32-bit armv7 as a supported architecture! I have no idea why this is the case. Removing it seemed to fix the problem.

Like this?

![Screenshot 2021-06-23 at 12 38 55](https://user-images.githubusercontent.com/24314029/123083313-3a794480-d420-11eb-8ada-c0707e480b20.png)

**Comment by bhigusa** [comment]
Open Xcode, <your project>, Build Settings, Build Active Architecture Only and change to <NO> for Debug and Release. Architectures set/leave in Standard Architecture -$(ARCHS_STANDARD), important is next step:
Valid Architecture: armv7, armv7s, arm64, arm64e, ADD here x86_64 and if you need add i386 for Debug and Release. (String: armv7, armv7s, arm64, arm64e, x86_64)

Choose any simulator in your simulator list and BUILT IT. DONE.

**Comment by archcorsair** [comment]
Today I ran into this problem on my M1 architecture machine and the solution for me was to have Xcode open using Rosetta.
<img height=750 src="https://user-images.githubusercontent.com/1036921/139515864-935dd4c1-5058-40a7-a7f8-1a5574673d97.png" />

**Comment by adriansergheev** [comment]
bump

**Comment by dorperezx** [comment]
same here, any updates ?

**Comment by NateFuller** [comment]
bump

**Comment by TacticCoder** [comment]
What work for me(React Native Project):

1. Create new react native project
- you may be able to skip step 2, i was have to do it because we try to change the swift setting for the lottie..
2. take the new project.pbxproj, move it to your project, and reenter you old settings again
3. go to ios folder and run the following command `arch -x86_64 sudo gem install ffi`

**Comment by pitoneux** [comment]
But if you don't use pod but use SPM, you get the same error.

**Comment by ls-philippe-casgrain** [comment]
> > Today I ran into this problem on my M1 architecture machine and the solution for me was to have Xcode open using Rosetta.
> > Edit: I'm using Lottie in a React Native context <img alt="" height="750" src="https://user-images.githubusercontent.com/1036921/139515864-935dd4c1-5058-40a7-a7f8-1a5574673d97.png">
> 
> This solved my issue, Thanks.

Do not open Xcode using Rosetta; that’s not a supported configuration.

https://developer.apple.com/forums/thread/700380?answerId=704660022#704660022

**Comment by mmiedlarz** [comment]
For me, adding following lines to the podfile fixed the issue:
```
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|        
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
end
```

**Comment by spaceod** [comment]
**Current Working Solution 🎉**

```
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
  end
```

**Comment by nikitaame** [comment]
This still isn't fixed for SPM! Could we please reopen and fix?

**Comment by QuangDevPro** [comment]
Nothing work

**Comment by MrRonanX** [comment]
Another shoutout to reopen this. The lottie doesn't work if installed via SPM

**Comment by jamesgathu** [comment]
As of XCode 14.3 the option for using Rosetta is not available by default. You can activate it for a specific project only as shown below

![image](https://user-images.githubusercontent.com/14311549/236060567-9d9fd820-1fd5-4c0e-a3dc-2cac37a79ae5.png)

**Comment by GustMelo** [comment]
Same here :(

**Comment by glennposadas** [comment]
My project is still fresh, so instead of beating airbnb to fix this working lottie or following the old proposed solutions here, I decided to retain the lottie through cocoapods and firebase stuff via SPM. I realized that Firebase frameworks cause all these troubles and conflicts with Lottie resulting to the discussed error message. 

My Podfile is as simple as this:

```
platform :ios, '15.0'

target 'BabyVision' do
  use_frameworks!
  
  pod 'lottie-ios', :git => 'https://github.com/airbnb/lottie-ios', :branch => 'master'
end
```

**Comment by ZacharyHandshoe** [comment]
This issue occurs whenever I try using Package Manager and cocopods

**Comment by seasonwu** [comment]
I fixed this problem by use Rosetta run simulator

**Comment by abinchy** [comment]
> As of XCode 14.3 the option for using Rosetta is not available by default. You can activate it for a specific project only as shown below
> 
> ![image](https://user-images.githubusercontent.com/14311549/236060567-9d9fd820-1fd5-4c0e-a3dc-2cac37a79ae5.png)

This works
