### ISSUE TITLE
Missing package product 'Lottie'

### ISSUE THREAD

**Issue by kampro** [airbnb/lottie-ios#1379]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Crashing Bug

## Which Version of Lottie are you using?

Lottie 3.2.3

## What Platform are you on? 

- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 

My project should build.

## Actual Behavior

I have an own SPM package which depends on Lottie (code from Package.swift below), the SPM package is linked to my iOS app, when I try to build the app the build fails with an error "Missing package product 'Lottie'". I have to click "Update to Latest Package Versions" several times (usually 2-3) to make it working, but this is a huge problem when we want to release our app through CI, we have to retry the job several times until it finally pass.
It happens when Lottie is added in Package.swift to our SPM package OR to the app via Xcode (the SPM tab). We have more dependencies and the problem exists only with Lottie.

## Code Example
A few lines from Package.swift
```
let package = Package(
    // (...)
    defaultLocalization: "en",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(
            // (...)
        )
    ],
    dependencies: [
        // (...)
        .package(name: "Lottie",
                 url: "https://github.com/airbnb/lottie-ios.git",
                 .upToNextMajor(from: "3.1.8")),
        // (...)
    ],
    targets: [
        .target(
            // (...)
            dependencies: [
                // (...)
                "Lottie",
                // (...)
            ],
            resources: [.process("Resources")]
        ),
        .testTarget(
            // (...)
            dependencies: [
                // (...)
            ]
        )
    ]
)
```

**Comment by jarod2d** [comment]
We're seeing the same issue as well using Lottie integrated via SPM in Xcode 12.5. It's triggered pretty consistently when switching branches in our repo. To add another data point, we see exactly the same problem with [BonMot](https://github.com/Rightpoint/BonMot), so it's not just Lottie with this issue, but it's definitely specific to certain packages.

In Xcode, we see a grayed out `lottie-ios` in the resolved package list as well as `Lottie`, as well as `bonmot` + `BonMot`. So it seems to me like there's some kind of SPM bug causing the package to sometimes be resolved under the wrong name.

I was initially thinking it had something to do with the repo name and package name being different because `lottie-ios` is the repo name and `Lottie` is the package name, but BonMot consistently uses `BonMot` everywhere, and some of our other dependencies also use different repo / package names.

<img width="414" alt="Screen Shot 2021-08-12 at 12 20 19" src="https://user-images.githubusercontent.com/189833/129256056-38203830-a02a-4fb6-99af-2b8bef043e78.png">

**Comment by kampro** [comment]
We investigated it more and it looks like SPM's bug.

**Comment by Jon889** [comment]
I have this same issue, to the point I've stopped using Lottie with SPM and switched back to using CocoaPods for it. It's definitely something specific to Lottie that is interacting badly with SPM. I don't think this can be discounted as just a bug in SPM.

**Comment by Jon889** [comment]
For some reason deleting all the Xcode defaults made this work: https://developer.apple.com/forums/thread/678974

`defaults delete com.apple.dt.Xcode`

**Comment by Jon889** [comment]
Specifically if you've `ShowBuildOperationDuration` to YES that seems to be the issue. So `defaults delete com.apple.dt.Xcode ShowBuildOperationDuration` worked for me.
