### ISSUE TITLE
Doesn't work with text animations?

### ISSUE THREAD

**Issue by sarperdag** [airbnb/lottie-ios#15]
Tried with the attached json file (in zip) that has a super simple text animation, but no no luck... What might be reason?

[text.zip](https://github.com/airbnb/lottie-ios/files/748845/text.zip)

**Comment by buba447** [comment]
Hey! We haven't yet implemented support for text layers. We're currently working out a strategy for supporting text layers while also supporting localization. Stay tuned!

Until then you can convert the text layer to a shape layer following the steps in this tutorial, its not perfect but it will get your text on screen for the time being!

https://www.premiumbeat.com/blog/quick-tip-converting-text-to-masks-in-after-effects/

**Comment by therealsalih** [comment]
You can also right click a text layer and select "Create Shapes From Text"

<img width="365" alt="screen shot 2017-02-05 at 11 14 37 am" src="https://cloud.githubusercontent.com/assets/5893643/22629079/5559c7b2-eb94-11e6-9a99-9bf768ab3e35.png">

There still might be some weirdness because Lottie doesnt yet support subtracting paths so letters like the "e" that have holes inside will just be filled.

<img width="128" alt="screen shot 2017-02-05 at 11 16 11 am" src="https://cloud.githubusercontent.com/assets/5893643/22629085/837e53f6-eb94-11e6-91ae-1d0699dbe6ec.png">

**Comment by johnkeese** [comment]
The following process, while tedious, worked for me.

1. Start with text in Illustrator (you might be able to pull in stuff from Sketch as well?)
2. Outline the text
3. For each character that requires "Merged paths" when outlining in After Effects place a hidden cut. This is easiest using the knife tool.
4. Import AI file into After Effects and "Create Shapes from Vector Layer"

![screen shot 2017-02-09 at 8 11 20 am](https://cloud.githubusercontent.com/assets/3217063/22786757/77d74aae-ee9f-11e6-99f4-b58224df65e2.png)

I've also run into issues using Pre-Comps. Seemed to work best when everything what in the root comp.

**Comment by buba447** [comment]
@johnkeese Precomps aren't yet supported! Were working on it though :)

**Comment by johnkeese** [comment]
@buba447 oh my bad. Good to know!

**Comment by anjanamta** [comment]
Gave path animation and mask to an image layer. Exported as json with bodymovin. But images are not loading. What might be reason?
