### ISSUE TITLE
Stoke appearing incorrectly on iOS, but works fine in desktop browser. 

### ISSUE THREAD

**Issue by akendall0103** [airbnb/lottie-ios#151]
Hello! I'm having some problems with an animation I created. My developers tested the JSON file on browser and it looked great. When they tested it in iOS, there was a glitch with the stroke animation. I've attached screenshots of the problem, and the AEP file. Any solves for this? Thanks! 
![final result](https://cloud.githubusercontent.com/assets/26144701/23515590/93bccab0-ff38-11e6-8f27-2bdbc20bc266.png)
![glitch_stroke](https://cloud.githubusercontent.com/assets/26144701/23515596/9631570c-ff38-11e6-8c46-cc524b34d1c6.png)
[download_complete.aep.zip](https://github.com/airbnb/lottie-ios/files/814376/download_complete.aep.zip)

**Comment by buba447** [comment]
Ohh it seems here that you are using the Effect 'stroke'
Lottie is built to support the after effects shape layers and not the video effects (since those don't vectorize very well).
To fix this create a shape layer for the checkmark and simply apply a stroke to the check mark.
Ive included an example AEP file that shows the difference.

First, heres the layer implemented the way you are currently doing it - With effects
<img width="504" alt="screen shot 2017-03-02 at 11 13 51 am" src="https://cloud.githubusercontent.com/assets/1163980/23522873/7d52a276-ff39-11e6-8b46-335a971b7cdf.png">
<img width="381" alt="screen shot 2017-03-02 at 11 14 19 am" src="https://cloud.githubusercontent.com/assets/1163980/23522877/8144099c-ff39-11e6-987a-066977662718.png">

And heres it implemented with shape layers
<img width="512" alt="screen shot 2017-03-02 at 11 13 56 am" src="https://cloud.githubusercontent.com/assets/1163980/23522887/8a1e13fa-ff39-11e6-975f-4a6b5a0cdde9.png">
<img width="377" alt="screen shot 2017-03-02 at 11 14 10 am" src="https://cloud.githubusercontent.com/assets/1163980/23522893/8d5b2256-ff39-11e6-803b-16b5302883d2.png">

Heres the altered aep file for comparison. 
[download_complete.aep.zip](https://github.com/airbnb/lottie-ios/files/814855/download_complete.aep.zip)

**Comment by akendall0103** [comment]
Thanks!
