### ISSUE TITLE
Are Radial Wipe Effects Supported?

### ISSUE THREAD

**Issue by JALsnipe** [airbnb/lottie-ios#152]
It does not appear that radial wipe effects are supported.  I understand that I can use a trim path instead of a radial wipe, but radial wipe support would be great to have.

**Comment by therealsalih** [comment]
Radial wipes aren't supported in neither Bodymovin or Lottie. But you can work around it like you said by using a trim path on an elipse
If you make the elipse size and the stroke width the same number it works exactly the same as a radial wipe

![mar-02-2017 20-40-14](https://cloud.githubusercontent.com/assets/5893643/23538523/b0a8539c-ff88-11e6-9ef1-b9f2666e86b6.gif)

**Comment by JALsnipe** [comment]
I don't see how closing this issue is constructive.  Are there no plans to support an enhancement for radial wipes?

**Comment by therealsalih** [comment]
I closed it mainly because radial wipe isn't supported by bodymovin. If bodymovin doesn't support it neither can Lottie. 

You can track bodymovin support here
https://github.com/bodymovin/bodymovin/issues/268

If Hernan ever decides to support it then we can reopen this issue and figure out how to get it working on iOS & Android

**Comment by PembaTamang** [comment]
hi, @therealsalih  have you posted your animation on lottie files?? I cannot make one myself and I really need it
