### ISSUE TITLE
The Core Animation rendering engine partially supports time remapping keyframes

### ISSUE THREAD

**Issue by smolskyaleksey** [airbnb/lottie-ios#1648]
version 3.4.0 master branch

Lottie/AnimationView.swift:1003: Assertion failed: Encountered Core Animation compatibility issues while setting up animation:
[Puke Splash_PRECOMP_02] The Core Animation rendering engine partially supports time remapping keyframes, but this is somewhat experimental and has some known issues. Since it doesn't work in all cases, we have to fall back to using the main thread engine when using `RenderingEngineOption.automatic`.
[Puke Splash_PRECOMP_02] The Core Animation rendering engine partially supports time remapping keyframes, but this is somewhat experimental and has some known issues. Since it doesn't work in all cases, we have to fall back to using the main thread engine when using `RenderingEngineOption.automatic`.

This animation cannot be rendered correctly by the Core Animation engine.
To resolve this issue, you can use `RenderingEngineOption.automatic`, which automatically falls back
to the Main Thread rendering engine when necessary, or just use `RenderingEngineOption.mainThread`.

**Comment by calda** [comment]
When using which rendering engine?

**Comment by smolskyaleksey** [comment]
> When using which rendering engine?
Yes. Any rendering engine worse than 2.5.3

**Comment by smolskyaleksey** [comment]
> Can you share your animation json?

[gemmic.zip](https://github.com/airbnb/lottie-ios/files/9093859/gem4me.zip)

**Comment by calda** [comment]
Performance of these animations seems great when using the Core Animation engine (0% CPU utilization, and a high framerate), is there a specific issue you were encountering?

**Comment by smolskyaleksey** [comment]
> Performance of these animations seems great when using the Core Animation engine (0% CPU utilization, and a high framerate), is there a specific issue you were encountering?

When you add all of this to vertical collectionView, one per cell and try to scroll up/down fps rate will be decrease

**Comment by pejato** [comment]
Hey @calda , our designers like to use time remapping, so this is something I'd be interested in getting support for and would be willing to work on if feasible.

Do you have more info on what the outstanding issues here are?

**Comment by calda** [comment]
We have an [implementation](https://github.com/airbnb/lottie-ios/blob/master/Sources/Private/CoreAnimation/Layers/PreCompLayer.swift#L110) of time remapping that sort of works, but only in simple cases.

Time remapping in Core Animation is complicated for a few reasons:

Every animation has keyframes with timing curves, which Core Animation uses to determine the current value of the property animated at any given time. You can think of these as an arbitrary function that takes the layer's current time value and outputs the value of the property at that time.

Time remapping is also a set of keyframes with timing curves. Time remapping is basically a function that takes a layer's current time value and outputs the remapped time value for its child layer.

To render this correctly, the time remapping of the parent has to be applied to the child _every frame_. The Core Animation engine doesn't currently operate on individual frames -- it only operates on the set of defined keyframes, and lets Core Animation itself interpolate the individual frames. But if we only apply the time remapping to the _keyframes_ that we create, then the output is incorrect in complex cases. To fix this we would need to manually interpolate the keyframes so we know the value at each frame, and then apply the time remapping to each of those frames.

Another obstacle is the direction in which we have to apply the time remapping. Time remapping is specifically a function from the parent's "local time" to the child's "local time". An example of this -- say you want the child's animation to go twice as fast. When the parent layer is at frame 10, the child's frame is at time 20.

Because of the architecture of the Core Animation engine, I think we have to answer this question in reverse. In the same example of making the child's animation go twice as fast, when computing a value of the child layer at frame 20 we have to know that we should actually be using the value originally intended to be used at frame 10. This requires taking the _inverse_ of the time remapping function, which I don't know how to do correctly (particularly when accounting for the timing curves).

**Comment by pejato** [comment]
Thanks for the informative reply Cal, it's very helpful 😄 Going to do a more thorough reading of Lottie's CA rendering code this weekend.

> This requires taking the inverse of the time remapping function, which I don't know how to do correctly

I'm not sure this is even possible if the time remapping function isn't invertible, which is a possibility, e.g. if we reverse and replay some frames like the second animation [here](https://helpx.adobe.com/after-effects/using/time-stretching-time-remapping.html), right?

**Comment by calda** [comment]
Fixed in https://github.com/airbnb/lottie-ios/pull/2286!
