### ISSUE TITLE
Core Animation rendering engine doesn't support `MatteType.invert`

### ISSUE THREAD

**Issue by centralmotion** [airbnb/lottie-ios#1655]
## Which Version of Lottie are you using?

Lottie 3.4.0
## Issue
Hello there! I was experimenting with 3.4.0 (Core Animation) on iOS and I noticed that animated track matte layers do not seem to animate when tested with 3.4.0 

I am exporting with Bodymovin V 5.9.0

Animated mattes may not be supported yet, I am not sure if this is the case!

Thank you for all your efforts! Looking forward to using 3.4.0! 

## Animation JSON

https://lottiefiles.com/113328-square-matte-test
Here is a test that I used to troubleshoot.

**Comment by calda** [comment]
Thanks for the report! Interestingly it looks like the main thread engine and core animation engine are both incorrect here 😆

| Main thread engine, and `.automatic` option | Core Animation engine |
| ---- | ---- |
| ![2022-07-19 12 09 17](https://user-images.githubusercontent.com/1811727/179829883-37756946-e025-4645-a966-5e640afe5309.gif) | ![2022-07-19 12 09 27](https://user-images.githubusercontent.com/1811727/179830085-d6d61ab7-cb4e-43bd-bdb8-b4ab764e191d.gif) |

The main thread engine renders the matte correctly, but doesn't animate the star shape. The Core Animation engine animates the shape correctly, but doesn't render the matte correctly.

Since `.automatic` and `.mainThread` both render the same as Lottie 3.3.0 and earlier, I wouldn't consider a bug. There are two useful related enhancements though:
 1. support the type of matte layer in the Core Animation rendering engine
 2. support matte animations in the Main Thread rendering engine (may not be necessary once this animation is fully supported by the Core Animation engine).

**Comment by centralmotion** [comment]
Thank you for the detailed reply! Which type of Matte should I choose when using animation in the Core Animation rendering engine?

**Comment by calda** [comment]
I think Core Animation may not support using entire layers as inverted masks, so it may not be possible to implement this using a Matte layer.

If you need to use an inverted mask, you could potentially use a Mask instead. Since those masks include a bezier path, we can invert it without any issues (supported as-of #1617).

**Comment by centralmotion** [comment]
@calda Just as a follow up I was able to link the mask of a layer to a rig I made with the 'Create Nulls From Path' script in After effects, set it to subtract and it worked!

**Comment by calda** [comment]
Cool! Thanks for sharing :)
