### ISSUE TITLE
Stroke init compilation errors

### ISSUE THREAD

**Issue by mavukz** [airbnb/lottie-ios#1685]
## Which Version of Lottie are you using?

Lottie 3.4.1

## Expected Behavior 
Build to succeed, (using XCode Version 13.4.1)

## Actual Behavior
<img width="737" alt="Screenshot 2022-08-01 at 09 41 23" src="https://user-images.githubusercontent.com/27406635/182100805-73e66d5d-aab0-430c-95f2-74477298e252.png">

**Comment by osmnnyldzz** [comment]
It's working on Intel. But is not working on M1 chip. 
I get the same issue.

**Comment by yusufaksu19** [comment]
Same happened to me on M1 chip

**Comment by calda** [comment]
I can't reproduce this compiler error on Xcode 13.4.1 on my M1 laptop. Could somebody share a sample project that reproduces this error?

**Comment by mavukz** [comment]
Hi @calda I have cleaned, rebuild and deleted derived data, this issue still persists on my main project. However it works on dummy projects

**Comment by calda** [comment]
@mavukz, could you share a copy of the project where you are consistently seeing this error? You could email it to me privately at cal.stephens@airbnb.com if you're unable to share it publicly.

**Comment by calda** [comment]
What Swift language version are you using? It looks like this could potentially be caused by a `try?` expression changing a `[DashElement]?` to a `[DashElement]??`. [SE-0230](https://github.com/apple/swift-evolution/blob/main/proposals/0230-flatten-optional-try.md) changed `try?` to not produce these types of double-wrapped optionals, but this was added in Swift 5.0. Is your project using the Swift 4 language mode? Lottie supports Swift 5.3+

**Comment by mavukz** [comment]
Hi @calda, You are a legend! I had a bit of an overlook on my end. at project level we were targeting swift 5 but at target level swift 4.2. I have bumped it up and its working 100%

Thank you for the support!
