### ISSUE TITLE
Playback speed of animation doesn't match preview

### ISSUE THREAD

**Issue by jfruits** [airbnb/lottie-ios#1703]
I have two animations that play at the right speed on android and web. The haha animation playback is too fast while the +1 animation is too slow on iOS.  

## Which Version of Lottie are you using?

Lottie 3.3.0

## Expected Behavior 

haha animation: 
![Kapture 2022-08-05 at 10 12 31](https://user-images.githubusercontent.com/83983983/183127633-da9dfa3c-f0ce-485c-911d-8a77f7d5c81e.gif)

+1 animation: 
![Kapture 2022-08-05 at 10 15 12](https://user-images.githubusercontent.com/83983983/183128159-af216acf-e99e-437a-9a7a-80a21db72d7a.gif)

## Actual Behavior

haha animation: 
https://user-images.githubusercontent.com/83983983/183128817-9949b9d4-7381-4cea-9426-b2175bec848e.mov

+1 animation: 
https://user-images.githubusercontent.com/83983983/183128809-e4b0223a-2a20-44eb-bc2b-51d195446311.mov

## Animation JSON

haha animation: https://assets2.lottiefiles.com/private_files/lf30_jnejqp6z.json

+1 animation: https://assets8.lottiefiles.com/packages/lf20_ipzcrdre.json

**Comment by calda** [comment]
When I test this animation locally using Lottie 3.4.1 it appears to play at the same speed as it does on https://lottiefiles.com:

![2022-08-05 14 38 04](https://user-images.githubusercontent.com/1811727/183212979-8be8ae42-fdb9-4c7f-9a2e-cbd5c1be0ac6.gif)

Could you check if this issue is still occurring if you update to the latest version of Lottie? If so, could you share a sample project that reproduces the issue? Thanks!
