### ISSUE TITLE
Animation Sequenced Wrong

### ISSUE THREAD

**Issue by Pretz** [airbnb/lottie-ios#176]
Hey All,

We're investigating Lottie for a new feature and found one of our animations renders differently in Lottie and bodymovin. The animation has two components that animate at offset times, but Lottie plays both at the same time.

Here's a zip of the json file we used with Lottie, an HTML file from bodymovin, and the original AEP file:
[Sparkle-Animation-Sample-Lottie.zip](https://github.com/airbnb/lottie-ios/files/851929/Sparkle-Animation-Sample-Lottie.zip)

If there are any modifications we could make to our animation to get it to play correctly, we'd love to know. Do you have any directions/recommendations for constructing animations that will be supported by Lottie other than bodymovin's documentation? Thanks!

This is how the animation appears in Lottie (I simply added the file to the example app):
![mar-17-2017 15-28-52](https://cloud.githubusercontent.com/assets/35043/24065303/376fdab8-0b27-11e7-8604-74013c95def2.gif)

And this is the intended animation, rendered in bodymovin here:
![mar-17-2017 15-29-39](https://cloud.githubusercontent.com/assets/35043/24065318/4ca5abc4-0b27-11e7-9bac-c1a2d4c45367.gif)

**Comment by therealsalih** [comment]
Hi @Pretz right now precomps in Lottie don't yet support offsetting. We'll be working hard to get this working soon, but in the meantime if you just use the layers instead of the precomps you can offset them to your hearts desire

<img width="1478" alt="screen shot 2017-03-17 at 4 16 59 pm" src="https://cloud.githubusercontent.com/assets/5893643/24066139/4c2c77c6-0b2d-11e7-9e5f-16d06e894265.png">

**Comment by gpeal** [comment]
@Pretz Fyi, this works on Android as of 2.0.0-beta1

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
