### ISSUE TITLE
Import shape layers from Illustrator

### ISSUE THREAD

**Issue by vikram-kumar** [airbnb/lottie-ios#186]
Hi all,
I tried importing shape layers from Illustrator into After effects, checked it in bodymovin render preview and it is showing correct output. But Lottie couldn't render these layers. Please help.

**Comment by therealsalih** [comment]
@vikram-kumar Can you attach your AE file?

**Comment by sureMOE** [comment]
@vikram-kumar 

Hey vikram, when you bring files in from Illustrator and make shape layers with them in After Effects,  it will create a lot of garbage groups and merge path usage for unnecessary reasons (it seems to be connected to the artboard's definition in illustrator). Clean up your layers in After Effects and remove the erroneous content and you should be fine.

**Comment by vikram-kumar** [comment]
Thanks sureMOE. The problem is solved.

**Comment by LucasGrv** [comment]
@sureMOE 

Hey ! :) 
What do you mean by " Clean up your layers in After Effects " ? What should I do ?

**Comment by sureMOE** [comment]
@LucasGrv 

When you bring Illustrator files into After Effects, the first thing you need to look for is right clicking on your Illustrator layers (bringing up the contextual menu) and you are looking for a menu option called "Create Shape from Vector Layers". Once you have chosen that, you will see your Illustrator layers hidden and it will have created shape layers in their place. When you get to this point (depending on which version of Illustrator you are using), you will need to go through the "Contents" of your shape layers and look for groups and merge path items and reduce and break down some of those groups. It appears that some versions of Illustrator creates empty groups and layers based around the size of the artboard and these pieces will mess up Lottie because it doesn't support merge paths. 

Let me know if you have any more questions!

**Comment by LucasGrv** [comment]
Thank you @sureMOE ! It works :)

**Comment by bahargh** [comment]
hello @sureMOE I really have a problem with layers shapes of illustrator , when I want to render with bodymovin. it is not perfect output and it is like fade shape after rendering. I saw you helped someone that it is need to go through the "Contents" of your shape layers and look for groups and merge path items and reduce and break down some of those groups. but unfortunately I couldn't understand what do you mean. could ypu please help me. Thanks.

**Comment by Sjennon** [comment]
Hey @sureMOE !

I am having the same issue.. When I try to Create a shape from my .ai file, it seems like the new shape is gone. I checked opacity and position and both seemed fine. I also checked the Contents and it should just contain the group which contains the fill.

![image](https://user-images.githubusercontent.com/6576878/47304030-cca06d80-d625-11e8-9942-16b10b5ebf01.png)

I have no idea whatsoever how to make the shape appear :(

**Comment by sureMOE** [comment]
Hey Shannon! I am not sure what's going on with the file and would have to
see the file itself to know why your shape isn't translating correctly. You
can feel free to send it my way. Also, if you haven't seen yet, Adam Plouff
has created an awesome extension/plug-in called Overlord...it is so much
easier and a nicer way to move files between AE and AI. Check it out here:
https://www.battleaxe.co/overlord/

It is well worth the purchase! Good luck!

Aaron
