### ISSUE TITLE
The Core Animation rendering engine currently only supports customizing color values

### ISSUE THREAD

**Issue by Danielyz21** [airbnb/lottie-ios#1861]
## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior 

Comply with current constraints

## Actual Behavior

Hello! 
I'm looking for a bit of assistance here as I'm fairly new to Lottie.
I bumped to [4.0.1](https://github.com/airbnb/lottie-ios/releases/tag/4.0.1)  hoping to get some performance improvements on a screen that uses a couple Lottie animations. 
I had no breaking changes but I'm facing an assertion that spits the following: 

`The Core Animation rendering engine currently only supports customizing color values` 

The message itself is clear but what I'm lacking is the vocabulary to discuss with the designer possible changes because just by looking at the JSON is hard for me to tell

What values should we be looking at (to avoid) to tackle this issue? Is it literally avoiding customisation on anything but colours? 

Thanks in advance! 

## Animation JSON

[water_container_glass.json.zip](https://github.com/airbnb/lottie-ios/files/10240609/water_container_glass.json.zip)

**Comment by calda** [comment]
This message is related to usage of the `animationView.setValueProvider` API, not any specific feature within the animation json file itself.

What value providers are you using to customize the appearance of your animation? Could you share some sample code?

If you don't need to use the value providers for this animations, you can work around the assertion by removing the value providers. Otherwise you could manually fall back to the main thread rendering engine for this animation by providing `configuration: LottieConfiguration(renderingEngine: .mainThread)` when initializing your animation view.

**Comment by Danielyz21** [comment]
Hey @calda ! Thanks for the swiftly response! 🙇‍♂️  I'll be back with some sample code shortly!

**Comment by Danielyz21** [comment]
Hi @calda 
Holidays got in the way 🎅 

Here's a snippet from the value providers we're using
valueProviders: [
                "Plus.Fläche 1.Opacity"       : FloatValueProvider(isPlusVisible ? 100 : 0),
                "icon_check.Transform.Opacity": FloatValueProvider(isChecked     ? 100 : 0)
                ]
 )
 
and then in our LottieAnimationView we simply iterate over those. 
I see an umlaut in one of them, do you think this causes problems?

**Comment by calda** [comment]
`FloatValueProvider`s aren't supported yet, we have an issue tracking this here: https://github.com/airbnb/lottie-ios/issues/1837

We should update this assertion to be more descriptive, I'll make sure to do that as well.

**Comment by Danielyz21** [comment]
Got it, thanks for the help! Will close this issue now 👍
