### ISSUE TITLE
Crash and AppStoreConnet error when using XCFramework file

### ISSUE THREAD

**Issue by SajjadKharrazi** [airbnb/lottie-ios#1868]
- when i added .xcframework file manually and upload my app to appStore, i got this error:
```
ITMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:

@rpath/Lottie.framework/Lottie
After you’ve corrected the issues, you can upload a new binary to App Store Connect.
```
- also it causes app to crash when build on physical device, but on simulator it does not

but without .xc everything is ok

**Comment by calda** [comment]
Can you share a sample project that reproduces this issue?

**Comment by SajjadKharrazi** [comment]
[crashlog-B2A8537C-07A0-4F97-A638-ABB9D84C9D02.txt](https://github.com/airbnb/lottie-ios/files/10269633/crashlog-B2A8537C-07A0-4F97-A638-ABB9D84C9D02.txt)
[crashlog-543AFD27-17E3-4D92-889D-4BCED2A9D7AD.txt](https://github.com/airbnb/lottie-ios/files/10269635/crashlog-543AFD27-17E3-4D92-889D-4BCED2A9D7AD.txt)

this is crash reports

**Comment by calda** [comment]
Can you share an example Xcode project where this issue occurs?

**Comment by SajjadKharrazi** [comment]
[LottieManually.zip](https://github.com/airbnb/lottie-ios/files/10269740/LottieManually.zip)

you should open it in physical device

**Comment by calda** [comment]
The problem is that `Lottie.xcframework` is not being embedded in the built application:

<img width="665" alt="Screen Shot 2022-12-20 at 10 01 50 AM" src="https://user-images.githubusercontent.com/1811727/208735174-910e9d2d-4075-461f-9f1e-d5c7b9ce6c5d.png">

It works correctly if you change it to "Embed & Sign":

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1811727/208735270-bd914266-c71f-44cd-a4f1-29b3b856f2da.png">

**Comment by SajjadKharrazi** [comment]
and what abour appstore connect error?

**Comment by SajjadKharrazi** [comment]
@calda
