### ISSUE TITLE
Snapshot of an animation is empty when using `.coreAnimation`

### ISSUE THREAD

**Issue by sarastro-nl** [airbnb/lottie-ios#1870]
Since Lottie 4.0.1 our snapshot tests (using [uber's snapshot kit](https://github.com/uber/ios-snapshot-test-case/)) are failing because when creating a still of the view the animation is not visible anymore while other views are. We don't have these issues when using the `.mainThread` engine but we would prefer using the enhanced `.coreAnimation` engine.

I created a small code snippet to explain the issue (I could've used the actual failing snapshot unit test but I could also reproduce the behaviour in a simpler way):

```swift
import UIKit
import Lottie

class ViewController: UIViewController {
    let animationView: LottieAnimationView = {
        let animation = LottieAnimation.named("arrow.json", bundle: Bundle.main)
        let animationView = LottieAnimationView(animation: animation, configuration: LottieConfiguration(renderingEngine: RenderingEngineOption.coreAnimation))
        animationView.frame = CGRect(origin: .zero, size: CGSize(width: 100, height: 100))
        return animationView
    }()
    let label = UILabel()
    let container = UIView(frame: CGRect(origin: CGPoint(x: 0, y: 50), size: CGSize(width: 100, height: 100)))

    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(container)
        container.addSubview(animationView)
        container.addSubview(label)
        label.text = "this is a text"
        label.sizeToFit()
        let image = container.asImage
    }
}

extension UIView {
    var asImage: UIImage? { UIGraphicsImageRenderer(bounds: bounds).image { layer.render(in: $0.cgContext) }}
}
```

When running this code the first frame of the animation shows perfectly:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/66166668/208677750-7d87d790-ad46-43a7-97eb-33555aa25fe2.png">

but making a snapshot of this view the animation appears empty.

What I also tried (but without any affect)
- other animations
- adding a delay before making the snapshot to make sure any layout cycle has finished (also tried `viewDidAppear`)
- storing this image to file to make sure that the Quick Look functionality of Xcode isn't failing
- taking a snapshot of different views in the hierarchy
- taking a snapshot of the layer of the container and any sublayer (so also the layers of the animation view itself)
- setting the `.currentProgress` to e.g. 0.5

## Which Version of Lottie are you using?

Lottie 4.0.1

## Expected Behavior  (the behaviour when using `.mainThread`)
<img width="438" alt="image" src="https://user-images.githubusercontent.com/66166668/208680880-c1831db3-a945-426b-b84b-a5d10cf33a2b.png">

## Actual Behavior
<img width="438" alt="image" src="https://user-images.githubusercontent.com/66166668/208680995-83cc959c-649b-4501-9594-c1f1fcf38a82.png">

## Animation JSON
Any animation will do.

**Comment by calda** [comment]
Thanks for the report. There's a discussion about this problem here: https://github.com/airbnb/lottie-ios/discussions/1769#discussioncomment-3860672

This is an inherent limitation of using `CAAnimation`s, and I'm not aware of any solution that we could use to fix this at the library-level.

The easiest workaround is to use the main thread rendering engine in cases where you know you need to render Lottie views as a snapshot. At Airbnb we do this by setting `LottieConfiguration.shared.renderingEngine = .mainThread` in our snapshot tests.

Another workaround is to render the image using `view.layer.presentation()?.render(in:)` instead of `view.layer.render(in:)`. The presentation layer is only available if the view is currently being rendered on-screen in a `UIWindow`, which can be tricky in headless use cases like snapshot testing (we've made this work though, [here's an example](https://github.com/airbnb/lottie-ios/blob/master/Tests/Utils/Snapshotting%2BpresentationLayer.swift#L40)).

**Comment by calda** [comment]
I'm going to close this issue since I don't believe it's fixable on our end, and since there are known workarounds. Feel free to continue the discussion here or in https://github.com/airbnb/lottie-ios/discussions/1769#discussioncomment-3860672 -- if you know any potential solutions we should investigate, please let us know!
