### ISSUE TITLE
Lottie 4.1.2 Apple silicon Macs support issue, links with libraries that are not present

### ISSUE THREAD

**Issue by simondelphia** [airbnb/lottie-ios#1935]
Updated to latest version and just got a message from App Store Connect about Lottie linking with libraries that are not present on Mac. Never had this issue before and wouldn't have expected it to pop up suddenly in a patch version update, so I assume it wasn't intentional.

## Which Version of Lottie are you using?

Lottie 4.1.2
(lottie-spm)

## Expected Behavior 
No App Store Connect build upload warnings

## Actual Behavior
Got the following message from Apple after upload:

> ITMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:
> @rpath/Lottie.framework/Lottie

**Comment by calda** [comment]
Thanks, will see if I can figure out what's going on. As an immediate workaround, you shouldn't hit this issue if you use lottie-ios instead of lottie-spm.

**Comment by calda** [comment]
Can you share more information about the configurations your app supports and where exactly you're seeing this error? Screenshots would be helpful. We'll need to find some sort of repro case. If you're able to make a sample project that reproduces this issue that would be very helpful.

**Comment by calda** [comment]
Is Lottie included in your app's "Frameworks, Libraries, and Embedded Content" section?

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1811727/214207893-5df7f329-9137-46cc-bbbc-df1f1107010e.png">

**Comment by simondelphia** [comment]
Yes Lottie is included there, haven't changed anything there recently anyhow besides switching to `lottie-spm`, haven't had this issue before.

Yes, Lottie 4.1.2 causes a failure when I use "My Mac" as a destination from Xcode. 

I tried 4.0.1, 4.1.0, 4.1.1, and 4.1.2 with "My Mac" + `lottie-ios` and they were all fine. 

I also got the failure when I used 4.1.1 from `lottie-spm`.

So it seems like `lottie-spm` has the problem.

**Comment by calda** [comment]
> Yes, Lottie 4.1.2 causes a failure when I use "My Mac" as a destination from Xcode.

What's the failure?

**Comment by simondelphia** [comment]
The same one you indicated, with a bunch more similar ones.

**Comment by calda** [comment]
Have you tried removing Lottie from the "Frameworks, Libraries, and Embedded Content" section and then adding it back? I'm pretty sure that error means Lottie isn't being embedded in the app binary.

I'm currently not able to reproduce this issue. Would you be able to share a project that reproduces this error? I'm especially interested in being able to reproduce the runtime crash when using the "My Mac" destination -- if you could share a project that reproduces that issue it would be very helpful.

**Comment by simondelphia** [comment]
I've just switched back to the lottie-ios repo. 

Might be relevant that the Lottie library is linked to a submodule in my project. 

If I have a chance I'll try to reproduce it.

**Comment by cameronehrlich** [comment]
This issue is still happening

**Comment by calda** [comment]
@cameronehrlich, can you share a sample project that reproduces this issue?

**Comment by cameronehrlich** [comment]
@calda I would need to setup a new app in AppStoreConnect in order to test a sample project to make sure it is reproducible, so it might not be able to do that for a few days.  In the meantime, I can briefly describe to you our setup.  
- We have a Xcode workspace that we are trying to migrate from Cocoapods to SPM.
- In the workspace, we have one Xcode project.
- That Xcode project has multiple modules within it. (feature modules, networking module, UI module, etc).
- We are trying to link Lottie with our UI module (so not the main target).
- We have the option to make the app available on Apple Silicon Macs enabled in App Store Connect.

Unchecking the Apple Silicon option on App Store Connect caused the validation warning go away.
<img width="1187" alt="Screenshot 2023-04-07 at 9 53 26 AM" src="https://user-images.githubusercontent.com/1508740/230646999-ccd05e9c-58a6-4738-97bc-02a025d56bd0.png">
