### ISSUE TITLE
[Core Animation] triggering assert on x/y scale values

### ISSUE THREAD

**Issue by timoninas** [airbnb/lottie-ios#2025]
## Which Version of Lottie are you using?

Lottie 4.1.3

## Expected Behavior 
The animation is playing

## Actual Behavior
The assert is triggered on the debug build, followed by the crash of the application

```Swift
Thread 1: Assertion failed: Encountered Core Animation compatibility issues while setting up animation:
[line 2] The Core Animation rendering engine doesn't support applying separate x/y scale values (x: 103.0, y: 110.0) to this stroke item (Stroke 1).
[line 2] The Core Animation rendering engine doesn't support applying separate x/y scale values (x: 100.0, y: 95.0) to this stroke item (Stroke 1).
[line 2] The Core Animation rendering engine doesn't support applying separate x/y scale values (x: 100.0, y: 110.0) to 
```

## Animation JSON
Can I send you animation by using mail? Because it is future production animation 👀
Tell me plz contact info

**Comment by calda** [comment]
Sure, can you email it to cal.stephens@airbnb.com?

**Comment by calda** [comment]
If you use `RenderingEngineOption.automatic` instead of `RenderingEngineOption.coreAnimation`, this animation will automatically fall back to using the Main Thread rendering engine instead. That's the recommended way to handle functionality that isn't supported by the Core Animation rendering engine.

**Comment by timoninas** [comment]
I've send on your email message. From dotruger.37@gmail.com

**Comment by calda** [comment]
Thanks, I took a look at this animation and the issue you're hitting. Fixing this limitation in the Core Animation rendering engine would require a significant amount of work, so I don't plan on making any changes here for now.

Since this works correctly when using `RenderingEngineOption.automatic`, I'm going to close this issue (since it isn't a bug).  Thanks for the report though, always good to see how the Core Animation rendering engine's limitations affect folks in practice.

**Comment by timoninas** [comment]
Thank you a lot!

**Comment by timoninas** [comment]
Can I help you with fixing issue?

**Comment by calda** [comment]
We'd have to find a different fix for [this issue](https://github.com/airbnb/lottie-ios/pull/1872/files) that doesn't require applying a scalar transform multiplier to the stroke width: https://github.com/airbnb/lottie-ios/pull/1872/files#diff-ae296ecd305cad6614e2838bb8146ef2e22ba43844e909d46268dead9577ad3aR321
