### ISSUE TITLE
Lottie 4.x.x is breaking full screen animation top and bottom (not filling)

### ISSUE THREAD

**Issue by mmdock** [airbnb/lottie-ios#2065]
## Summary
Issue works as expected in 3.4.4 and 3.5.0.  No changes to LottieConfiguration.shared after update to 3.5.0 from 3.4.4.  
However, updating to any 4.x.x version will break this animation.
Snapkit library is used to set UI.  

## Which Version of Lottie are you using?
Lottie 3.5.0 (for correct example)
Lottie 4.x.x (for broken example)

## Expected Behavior 
For the animation to go full screen, not cutting off on the top and on the bottom.  Correct example here:

<img width="577" alt="Screenshot 2023-05-15 at 6 12 25 PM" src="https://github.com/airbnb/lottie-ios/assets/2423465/be8f49b6-853b-4856-b5d5-0c9dcc1b22d0">

## Actual Behavior

<img width="514" alt="Screenshot 2023-05-15 at 6 11 23 PM" src="https://github.com/airbnb/lottie-ios/assets/2423465/e81f113a-46d1-44f5-b54c-3ee7ad7b628c">

here you can see that the the animation is not going completely to the top and bottom.  The grey area above and below is actually the background color `self` in the code snippet

## code usage snippet
```Swift
    lazy var thirstModeActivation: LottieAnimationView = {
        let view = LottieAnimationView(animation: LottieAnimation.named("thirst_mode_activation"))
        return view
    }()

    func playAnimation(completion: @escaping () -> Void) {
        self.addSubview(thirstModeActivation)
        thirstModeActivation.snp.makeConstraints { make in
            make.edges.equalToSuperview()
            make.center.equalToSuperview()
        }
        self.thirstModeActivation.play { _ in
            completion()
        }
    }
```
## Animation JSON

json uploaded as txt
[thirst_mode_activation.txt](https://github.com/airbnb/lottie-ios/files/11483250/thirst_mode_activation.txt)

**Comment by calda** [comment]
I'm able to achieve the sort of layout you're looking for by constraining the `LottieAnimationView` to be full-screen and configuring `animationView.contentMode = .scaleAspectFill`.

<img src="https://github.com/airbnb/lottie-ios/assets/1811727/43328b95-1080-41dd-a09a-e3942f9f46ed" width=350>

Since that seems to work as expected, I'm going to go ahead and close this issue. If you think this is a bug we should investigate, please share a sample Xcode project that demonstrates the problem and re-open the issue.

**Comment by mmdock** [comment]
@calda  shouldn't the animation fill the animationview by default? why is the default to not fill the animation view?

**Comment by calda** [comment]
`LottieAnimationView.contentMode` defaults to `scaleAspectFit`. Based on the git history `scaleAspectFit` has been the default since at least 2019.

We did change `LottieAnimationView` to clip its sublayers to bounds by default recently (I think in Lottie 4.0). You can change back to the old behavior setting `animationView.maskAnimationToBounds = false`. They have have been what caused this change on your end, but I can't tell for sure without a sample project. (When I use `animationView.contentMode = .scaleAspectFill` in our sample project I don't also need `animationView.maskAnimationToBounds = false`, but this could be because out projects are set up differently).
