### ISSUE TITLE
Library not loaded: @rpath/Lottie.framework/Lottie

### ISSUE THREAD

**Issue by Semty** [airbnb/lottie-ios#2233]
I finally managed to reproduce the issue with a test project which you can find below. 

The project structure can be explained like this:
1. Main project with one CocoaPods dependency embeds and signs a framework that is located in another project
2. The framework has a `lottie-spm` package imported

## Which Version of Lottie are you using?
`lottie-spm 4.3.3`

## Expected Behavior 
No crash on device

## Actual Behavior
Crash on device:
- `Library not loaded: @rpath/Lottie.framework/Lottie`

## Thoughts
If we go to `DerivedData>Build>Products>Debug-iphoneos`, we'll see the following files:
- `_LottieStub.o`
- `_LottieStub.swiftmodule`
- `Lottie.framework`

I'm not sure why it is generated this way with a `.framework` folder (e.i. as a dynamic framework). 
AFAIK, all dynamic frameworks should be embedded and signed inside the main project in order to work properly, so we can check it here:
- `DerivedData>Build>Products>Debug-iphoneos>ProjectName>Frameworks`
    
When we go there, we only see one CocoaPods framework and one framework that we created inside our project, but no `Lottie.framework`.

This fact, I think, explains the crash, but not the underlying reason.
If, for example, we just create a custom shell script that copies and signs `Lottie.framework` to the path mentioned above, the crash is gone.

## Test Project
[LottieTestApp.zip](https://github.com/airbnb/lottie-ios/files/13400508/LottieTestApp.zip)

**Comment by calda** [comment]
Thanks for the detailed report.

You're correct that Xcode is unexpectedly not including the `Lottie.framework` in the `Frameworks` directory of the built application. I see two ways to fix this:
 1. You can open Derived Data, and drag the `Build/Products/Debug-iphonesimulator/Lottie.framework` file "Frameworks, Libaries, and Embedded Content" pane for your application target.
 2. Like you mentioned, you could add a custom shell script that copies the `Lottie.framework` into the `Frameworks` directory in the built application.

Both of these workarounds make it so the built application includes `Lottie.framework` in its `Frameworks` directory, so is able to run as expected.

This appears to be a bug in how Xcode handles Swift Package Manager dependencies which themselves have binary target dependencies. I'd suggest filing a feedback with Apple with this detailed bug report which demonstrates the issue.

Since this is likely an issue with Xcode itself, and there are suitable workarounds we can configure in the Xcode UI, I'm going to close this issue.

**Comment by calda** [comment]
I linked to this issue from https://github.com/apple/swift-package-manager/issues/6069, which is a related bug report on Swift Package Manager.

**Comment by Jon889** [comment]
This seems like quite a big deal, maybe it would be best to at least add a warning in the lottie-spm repo. As I understand it the lottie-spm package works if you add it directly to the app, but not if you add it to a framework used by the app? (if it doesn't work even if added directly to the app then the lottie-spm repo should be avoided completely then)

Or could the package.swift in the lottie-spm repo have the stub target added to it until SPM fixes this?

**Comment by rzulkoski** [comment]
It looks like you can fix this issue by adding `@executable_path/Frameworks` to your target's "Runpath Search Paths".
