### ISSUE TITLE
JSON output not matching Normal AEP output

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-ios#260]
Hey guys, 

I've been trying to troubleshoot a number of issues with the JSON output of this looping animation. 

Any help would be appreciate.

best,
-S

Issues I'm running into:
1. Playback is not smooth in JSON
2. Glitches are appearing during playback in iOS emulator
3. The sweep of lines from the pie chart back to the loader is cutting out in the JSON movie.
4. JSON Pie chart not same thickness as in AEP pie chart 

Sample Image of AEP Pie Chart Build layer
![pie element build technique](https://user-images.githubusercontent.com/29287850/27106290-91a064a2-5047-11e7-8601-fec730149903.png)

JSON Playback
![json_playback](https://user-images.githubusercontent.com/29287850/27141021-f0abdc26-50db-11e7-977d-efed31e9393a.gif)

Normal AEP Output
![2017_022_loader_icn_400px_v12](https://user-images.githubusercontent.com/29287850/27106008-7d60147a-5046-11e7-8a21-cc4c9ee38f6c.gif)

**Comment by therealsalih** [comment]
Hi @samiam2017 Can you send the AE file so we can see how its built and troubleshoot with you? As far as the framerate, try simulating on your device. Sometimes things are a bit choppy in my simulator because i've got other things going on my machine, but then when i simulate on my device its smooth...

**Comment by buba447** [comment]
Hello! Sorry youre having troubles! I cant fully debug without loading the file up in lottie and checking out the After Effects file, but from what I can tell youre probably experiencing these issues.
1. We have some issues with trim paths offsets, mainly when the paths loop over. This can be fixed by duplicating the layer in after effects and splitting the animation across bother layers.
2. I think, but im not sure, that the visual glitches come from paths adding control points over time. Ive seen this in the past, but without seeing your ae file i cant be sure. Usually morphing animaitons add arbitrary points during the morph, on ios we dont currently support that, a path must have all of its points from the start.

**Comment by buba447** [comment]
An example can be found here https://github.com/airbnb/lottie-ios/issues/247

**Comment by samiam2017** [comment]
Thanks for the feedback guys. Here is the ae file. 

[Loader_TestShare.zip](https://github.com/airbnb/lottie-ios/files/1081300/Loader_TestShare.zip)

**Comment by therealsalih** [comment]
Hi @samiam2017 I've taken a look at your file, heres a few things:

Lottie iOS doesn't yet support Alpha inverted mattes. You're using those on the first 6 layers, thats why  the thickness isn't carrying over
![image](https://user-images.githubusercontent.com/5893643/27235688-9aaa9712-5276-11e7-959b-4ca7fb85706f.png)

Your comp size is 2000x2000. Thats quite a large size. Generally its suggested to work at 1x. If you take your size down to 200x200 (or whatever the 1x size is, you should see better performance)

![image](https://user-images.githubusercontent.com/5893643/27235715-bd3f957a-5276-11e7-9691-8c65f383ce9f.png)

you also have some layers shyed and hidden but are still being calculated even though they arent visible, which is probably impacting performance. "Shape Layer 3" is an example of that. Its got a bunch of large mattes, all being rendered at larger than 2000x2000 and all being drawn every frame. So you should go through and clean up your composition so there aren't any layers like this

![image](https://user-images.githubusercontent.com/5893643/27235797-15201f1c-5277-11e7-85af-bd3928c47f79.png)

Lastly, you've got a layer or two that is adding new points during the animation. Right now Lottie iOS has problems when a path is adding or removing points during the animation. You'll always get some funky results when that happens

![jun-16-2017 09-51-09](https://user-images.githubusercontent.com/5893643/27236329-75977550-5279-11e7-87ca-e606416d9553.gif)

If you address each of these things by using different solutions your animation should come out great. Thanks!

**Comment by samiam2017** [comment]
Hey guys the feedback was super helpful, thank you!  

I'm still running into some issues with the refined version of the project. If you look at the screen grabs the pie chart is still having the issue of smoothly going back into the loader. Let me know if you can think of a solution. 

screen grab of pie not aligning
![pie not aligning](https://user-images.githubusercontent.com/29287850/27247796-e123ef60-52b0-11e7-9cd2-8364a40aa5a3.png)

what it's looking like
![2017-06-16_16-14-06](https://user-images.githubusercontent.com/29287850/27247829-30efbb00-52b1-11e7-83e7-fd5a45500107.gif)

current project build
[ExFd_test_3.zip](https://github.com/airbnb/lottie-ios/files/1082166/ExFd_test_3.zip)

**Comment by therealsalih** [comment]
I took a look at your file and this looks to be a Bodymovin issue... I'll send this issue to Hernan, the bodymovin creator. If you wouldn't mind can you make a separate ticket on the [bodymovin github page](https://github.com/bodymovin/bodymovin)?

**Comment by therealsalih** [comment]
@samiam2017  I actually think i see what the issue is. You're using Offset paths, which doesn't look like its supported by Bodymovin
![image](https://user-images.githubusercontent.com/5893643/27308979-52123810-5506-11e7-9304-8eeaef1110e6.png)

If you get rid of all of the offset paths in your project and readjust the layers using scale or something else it should work

**Comment by samiam2017** [comment]
@therealsalih thanks! I will test it out. Thanks again for all your help.

**Comment by samiam2017** [comment]
@therealsalih I think this is a Lottie issue. Bodymovin has a slight strobing effect on the transition, but on iOS and Android using the lottie library the transition just cuts out.

Any work arounds you'd recommend would be appreciated.  

[test_3d.zip](https://github.com/airbnb/lottie-ios/files/1088973/test_3d.zip)

**Comment by therealsalih** [comment]
if you trim your comp to the work area it should work
![image](https://user-images.githubusercontent.com/5893643/27346036-a58e306c-55a0-11e7-96b4-5ae1b698fb69.png)

We'll look into why thats happening even if you don't trim it

**Comment by therealsalih** [comment]
Also be sure to extend the visible layers out past the last frame

![image](https://user-images.githubusercontent.com/5893643/27346079-d53c42ea-55a0-11e7-89cf-411ed15c38b6.png)

![image](https://user-images.githubusercontent.com/5893643/27346084-dae1cfd0-55a0-11e7-86d6-89e165e1bc33.png)

**Comment by samiam2017** [comment]
Mission Accomplished!!! Thanks @therealsalih !!!
