### ISSUE TITLE
Part of the frames are not displayed

### ISSUE THREAD

**Issue by Nikita2k** [airbnb/lottie-ios#310]
Hi! I'm testing on **iOS10** with Lottie version 1.5.2 (installed with Carthage).

Animation in previewer works as expected, but when it comes to iOS frames after the "phone" are not displayed, but I can just see empty screen.
https://www.lottiefiles.com/share/2U5Nwn

Json file is attached:
[loading animation_Jul20.json.zip](https://github.com/airbnb/lottie-ios/files/1162304/loading.animation_Jul20.json.zip)

Also exporting only frames after the phone helps (displays as expected).

Any ideas?

**Comment by michaelgum** [comment]
@Nikita2k Can you upload the AE file?

**Comment by jlfuller** [comment]
@michaelgum I just tried uploading, but received an error that github doesn't support AE files. Can you provide an email I could send it to?

**Comment by jlfuller** [comment]
[iOS loading.aep.zip](https://github.com/airbnb/lottie-ios/files/1171904/iOS.loading.aep.zip)

@michaelgum please see this AE file

**Comment by michaelgum** [comment]
It looks like it is because your precomps do not start at 0. It is a known issue that all precomps start playing at 0; offsetting of precomps doesn't currently work.
You can offset the animation inside of the precomp to fix the issue. Please see the attached AE file.

Is this closer to how it is supposed to look?
https://www.lottiefiles.com/share/sNaN8H

[iOS loading - 02.aep.zip](https://github.com/airbnb/lottie-ios/files/1173290/iOS.loading.-.02.aep.zip)

**Comment by buba447** [comment]
Please see here
https://github.com/airbnb/lottie-ios/issues/290

**Comment by jlfuller** [comment]
@michaelgum @buba447 Yes this works, thanks for the fix!

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!
