### ISSUE TITLE
Lottie to OpenGL

### ISSUE THREAD

**Issue by kopacabana** [airbnb/lottie-ios#319]
Hello,

Thanks for Lottie. Very nice animation tool.
Sorry for my awful english :)

I want to use Lottie in an OpenGL context. I try to make a screenshot of LOTAnimationView but there is just one shape in my screenshot.
If I make a screenshot with drawHierarchy, all my shapes is OK but it's very slow (framerate change from 60fps to 25fps).

Is it possible to add a public **property** or **function** that **return cgImage** of all shapes or a **method** that can add **Lottie data** to **OpenGL buffer** ? This would be fantastic !

Thanks for your response.
Loïc

**Comment by buba447** [comment]
Sorry, Lottie renders within the CoreAnimation library. I have yet to find a clean or efficient way to get UIKit backing data over to OpenGL. All of the ways to render out CALayers that I know of are pretty slow.

**Comment by kopacabana** [comment]
Hi,

Thanks for your reply.

Loïc

2017-08-04 20:04 GMT+02:00 Brandon Withrow <notifications@github.com>:

**Comment by mofarhand** [comment]
@kopacabana  @buba447 
I've tried the same approach in obj-c but it doesn't work for me for some reason ...
the problem is I'm passing
self.animatedControl.animationView
but the picture is the first frame and I can't get the correct UIImage of the current frame!
how Can I get the screen shot from current state of animationView?
