### ISSUE TITLE
Reopened - Animation call back is not invoked when app is sent to background and put to foreground in the middle of animation in v2.0.3 & v2.0.4

### ISSUE THREAD

**Issue by venkatanavn** [airbnb/lottie-ios#370]
I recently updated the Lottie SDK from v1.5.1 to v2.0.3. I see an issue on the new v2.0.3 and v2.0.4... This issues is not there in v1.5.1

Steps to reproduce:

Play the animation using the below method
func play(completion: Lottie.LOTAnimationCompletionBlock? = nil)
Dismiss the app to background in the middle of animation.
Open the app again (i.e. get to foreground)
Now observe that the completionBlock is not invoked.
Please let me know.

**Comment by buba447** [comment]
@venkatanavn Ive fixed the completion block issue in the forthcoming Lottie 2.0.5.
If you background the app the animation will stop at its current point and the completion block will be called with NO as the argument.

This is the expected behavior, and how all caanimaitons work.

If you want for the animation to pause and then start again after coming back you should call pause and start from the appropriate methods.

**Comment by buba447** [comment]
This is fixed in 2.0.5! Please Update and verify!

**Comment by venkatanavn** [comment]
Fixed..Thank you @buba447

**Comment by venkatanavn** [comment]
Hi @buba447 , I see this again in v2.0.5...
