### ISSUE TITLE
View added through the function `addSubview:toLayerNamed:applyTransform:` has incorrect size

### ISSUE THREAD

**Issue by YK-Unit** [airbnb/lottie-ios#382]
**version:** lottie-iOS v2.0.5

**issue:** View added through the function `addSubview:toLayerNamed:applyTransform:` has incorrect size.

**Comment by buba447** [comment]
I need a bit of information here?
The view should maintain its frame that is set before adding. Can you give me more information?

**Comment by YK-Unit** [comment]
Here is my code
``` objc
   self.switchButton = [LOTAnimationView animationNamed:@"Switch"];
    self.switchButton.contentMode = UIViewContentModeScaleAspectFit;
    //switchButton的width和height从AE文件中获得
    self.switchButton.frame = CGRectMake(10, 100, 216/2, 116/2);
    UITapGestureRecognizer *switchButtonTapGR = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(switchButtonClicked)];
    [self.switchButton addGestureRecognizer:switchButtonTapGR];
    [self.view addSubview:self.switchButton];
    [self.switchButton setValue:[UIColor orangeColor] forKeypath:@"Background 2.Shape 1.Fill 1.Color" atFrame:@(0)];
    [self.switchButton setValue:[UIColor blueColor] forKeypath:@"Background 2.Shape 1.Fill 1.Color" atFrame:@(13)];
    [self.switchButton logHierarchyKeypaths];

    UIView *dotView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 20, 20)];
    dotView.backgroundColor = [UIColor darkGrayColor];
    dotView.layer.cornerRadius = 10;
    [self.switchButton addSubview:dotView toLayerNamed:@"On Indicator" applyTransform:YES];
```
Here is the AE-FILE and JSON-FILE :
[AE-FILE and JSON-FILE.zip](https://github.com/airbnb/lottie-ios/files/1247469/AE-FILE.and.JSON-FILE.zip)

**Comment by buba447** [comment]
@YK-Unit And what do you expect it to look like vs what does it look like?

**Comment by buba447** [comment]
@YK-Unit I figured it out.
Theres definitely a bug in Lottie. I may to have to change the API slightly too. 

In the meantime theres a work around!
So the bug is caused by some bad coordinated transform math, to fix it you can add a null layer that is positioned at 0,0 to your comp and parent it to the Off Indicator layer and make sure that you set the opacity to 100 (Null layers default to 0). Then add your custom view to the null layer. Ive included an AEP that does just this as an example, the new layer is called `DotParent`. 

When you add the sublayer it will be positioned on the first frame at the origin you specify for its frame. So for a frame of `CGRectMake(0,0,20,20)` the dot will be positioned in the top left hand corner.  To move it elsewhere, change its origin before adding it to the Lottie view.

<img width="716" alt="screen shot 2017-08-24 at 11 43 05 am" src="https://user-images.githubusercontent.com/1163980/29682991-c2037b04-88c1-11e7-9a65-381c3ab0e8d3.png">
The new Null layer, before parenting set its position to `0, 0` and its opacity to `100`
Then parent it to the `Off Indicator` layer.

Now using your code to add the dot, with a frame of `CGRectMake(0,0,20,20)` you will get a dot positioned like so.
<img width="220" alt="screen shot 2017-08-24 at 11 42 41 am" src="https://user-images.githubusercontent.com/1163980/29683083-0a5ae612-88c2-11e7-984f-bb723211330c.png">

To move the dot elsewhere set its frame to something like  `CGRectMake(50,50,20,20)` before adding it.

Heres the AEP file with the new Null layer
[NewSwitch.zip](https://github.com/airbnb/lottie-ios/files/1249929/NewSwitch.zip)

**Comment by buba447** [comment]
@YK-Unit Fixed further with recent update
