### ISSUE TITLE
Contrast / Blur

### ISSUE THREAD

**Issue by slane2016** [airbnb/lottie-ios#386]
Hi We're looking to add a liquid motion effect and need blur/contrast filters via AE. The exports works but then the filters don't work. Any chance you'll be supporting these filters with future releases?

**Comment by buba447** [comment]
No plans on supporting filters in the future. You could, however, add a VisualEffectsView over your LOTAnimation to achieve a similar effect. 

https://www.raywenderlich.com/84043/ios-8-visual-effects-tutorial

Unfortunately the visual effects view doesnt give many options to alter the blur, which is why its unsupported officially in Lottie
