### ISSUE TITLE
Touch Events on Animation Layers

### ISSUE THREAD

**Issue by kyle-fox** [airbnb/lottie-ios#496]
## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.1.4)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [X] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

Is this currently possible? I attempted to sort of accomplish this by adding a UIView with a tap recognizer as a subview of a specific layer with: `- (void)addSubview:(nonnull LOTView *)view toLayerNamed:(nonnull NSString *)layer applyTransform:(BOOL)applyTransform`, but I couldn't quite get that to work. Am I headed down the right path to make this happen?

**Comment by buba447** [comment]
Ive been thinking a lot about this recently. It is possible, but will require some work to accomplish. The subview to layer doesnt work because, as far as I know, CALayers dont handle touch events.

**Comment by oojojjeoo** [comment]
I've done this by holding a reference to the view being added to the LOTAnimationView and using a second view to do the touch event on and then doing the same calculations on the lottie subview.

**Comment by wirnico** [comment]
I stumbled upon this thread because I am trying to implement a touchable view/button to a layer of a Lottie animation. Can you give me a hint how you solved that or is there meanwhile a function to get this done?
I implemented the views to layers with this standard code:
animationView?.addSubview(view: UIView, toKeypathLayer: LOTKeypath)

But for this, is not touchable.
I also thought about a way to implement a separate view and pin that to a layer. But I don't see a way to get the coordinates of a Lottie layer.

Thanks in advance. Would really appreciate some help.

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
