### ISSUE TITLE
logHierarchyKeypaths doesn't show anything

### ISSUE THREAD

**Issue by dev4dev** [airbnb/lottie-ios#556]
## Check these before submitting:
- [] Updated to the latest version of Lottie (2.1.5)
    **nope, it's version 2.5.0, you've forgot to update it in podspec to 2.5.1***
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [] MacOS
- [x] iOS

## Expected Behavior 

`logHierarchyKeypaths()` method reports nothing, thus I can't customize visual representation of an animation

## Code Example

```swift
let lot = LOTAnimationView(name: "transloader")
lot.logHierarchyKeypaths()
```

## Animation JSON

https://www.lottiefiles.com/315-loader-ring

**Comment by jarrettc124** [comment]
Hey there!

If you look into the logHierarchyKeypaths() function, you'll notice that it uses NSLog to log out files. If you're using Swift, that could be the issue of why it's not showing up on the console since lottie-ios is bridged from Objective-C to Swift.

Just simply recreate the function and provide a "print()" instead of "NSLog"

Example:
`        
let loadView = LOTAnimationView(name: "loading_icon") //Your loading .json file
let keypaths = LOTKeypath(string:"**") //Get all keypaths with **
let keys = loadView.keys(forKeyPath: keypaths) as? [String] //get all keys

print("Keys shown below:")
for k in keys{
   print(k)
}`

That should do it (Hopefully) 😄

**Comment by buba447** [comment]
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
