### ISSUE TITLE
Lottie for Loading Animations Compared to UIActivityIndicatorView

### ISSUE THREAD

**Issue by adamkhazi** [airbnb/lottie-ios#768]
Hi everyone!

I have been using Lottie for the last week and came across an issue with it in an app I am working on. I have a loading or activity spinner created using Lottie. I display the loading spinner when a user is logging into the app among other places. I've noticed that my spinner stutters quite a lot when other work is being done on the main thread such as object initialisations. I have also removed other tasks using the main thread and let the Lottie loading spinner run by itself to verify that the spinner itself animates smoothly. From using the Core Animation instrument on Xcode I was able to see that Lottie is rendering individual frames and some part of this processing is done on the main thread while the animation is playing.

When comparing against the `UIActivityIndicatorView`. I have noticed that the main thread is not as busy as with the Lottie version. Additionally I've noticed that when the Lottie loading spinner animation is running if I pause the app in the debugger the Lottie animation freezes. But if I do the same with the `UIActivityIndicatorView` it does not.

I was wondering if there is a way around this i.e., make it behave similarly to `UIActivityIndicatorView`?

## Check these before submitting:
- [X] Updated to the latest version of Lottie (2.5.0)
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## What Platform are you on? 

- [ ] MacOS
- [X] iOS

**Comment by buba447** [comment]
There are a lot of ways to improve the performance of your animation. Some ways to improve the performance of you animation:
- Remove Masks, use shapes instead.
- Remove alpha mattes
- Remove Gradients
- Reduce any path animation. For instance if you are simply moving the path, use the transform instead of adding keyframes to the path itself

I hope this helps! Also just to note the new version of Lottie (3.0) is a complete rewrite in swift. You may have performance increases by updating.
