### ISSUE TITLE
need load from json

### ISSUE THREAD

**Issue by myeveryheart** [airbnb/lottie-ios#792]
I see the change:
LOTComposition.animationFromJSON: | ⛔️(Animation is Encodable/Decodable from data on it's own.)
-- | --
The problem is, sometimes the json string is passed from js to native. So if there's only load from file, I hava to save the json string to file, than read from file, which is slow.

**Comment by buba447** [comment]
You can still load it from json that is in memory, lottie just handles the decoding for you.
Animation can be decoded from any valid json data. Lottie decodes the json directly into the model instead of having to pass through an intermediary, which helps performance quite a bit.

If you have any troubles please see this part of the readme: https://github.com/airbnb/lottie-ios#loading-animation

**Comment by myeveryheart** [comment]
@buba447 hi, thanks for answering. But I didn't find a api that can read from jsonString.

**Comment by buba447** [comment]
@myeveryheart You just need to convert the string to data:
```
let data = String(data: bytes, encoding: .utf8)
let animation = try JSONDecoder().decode(Animation.self, from: data)
```

**Comment by myeveryheart** [comment]
@buba447 thank you very much.
