### ISSUE TITLE
Attempting to play looping animations in viewDidLoad fails

### ISSUE THREAD

**Issue by kyle-fox** [airbnb/lottie-ios#811]
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.1

## What Platform are you on? 

- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 

Starting the animation in either `viewDidLoad` or `viewWillAppear` have same behavior.

## Actual Behavior

Starting animation in `viewDidLoad`, which worked before 3.x, returns false immediately. Starting animation in `viewWillAppear` works as expected.

## Code Example

Some snippets approximating what I'm doing - hopefully this will help! The animation is usually in a separate struct, so you can ignore `insertSubview` being separate from the creation of the animation. Wanted to keep it as close to what I have as possible.

```
static let animationName: AnimationView = {
    let animation = AnimationView(name: "animationName")
    animation.loopMode = .loop
    return animation
}()

override func viewDidLoad() {
    super.viewDidLoad()
    // Doesn't play the looping animation. The `LottieCompletionBlock` in play returns false.
    setupLottieAnimations()
}

override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    // Looping animation plays. The `LottieCompletionBlock` in play isn't called.
    setupLottieAnimations()
}

func setupLottieAnimations() {
    view.insertSubview(animationName, at: 0)
    animationName.play { finished in
        print(finished)
    }
}
```

**Comment by buba447** [comment]
Hey @kyle-fox I setup a project with your code and everything seems to be working fine for me.
Some things to note,

If I comment out either of the `setupLottieAnimations()` then the one left behind will behave as expected. What is happening when both are left in is that the second call to `play` is cancelling the first call to `play` which causes it to call its completion block with `false`. This is actually the expected behavior. It 'worked' in previous version because we had some pretty bad edge cases and errors with the completion block logic that was providing this bug/feature. 

An animation that is looping will not call the completion block until the animation quits playing. Or at least thats how its setup now. Did it previously call the completion block once it played through once, even though it kept playing? One thing you can do it set loop mode to playOnce, then in the completion restart the animation with a loopMode of loop. Theoretically it that should work and be smooth.


Ive provided my test project below. Feel free to make changed and respond with any questions/continued problems.
[Example.zip](https://github.com/airbnb/lottie-ios/files/2993487/Example.zip)

**Comment by kyle-fox** [comment]
Thanks for the quick response! Sorry for the confusion - one of these *is* meant to be commented out at any given time, i.e. I'm not calling them both. I'll check out your example project and see if I can get it to reproduce. If it changes anything, the view controller that is implementing this animation is one that is being presenting modally.

**Comment by buba447** [comment]
If you can get a repo working in the example project send it to me and Ill sort it out!

**Comment by kyle-fox** [comment]
Double checked, and play is only being called once, so I'm ok there. But, I see that in the example, although false is returned, the animation plays as expected. In my case, the animation isn't playing at all. I'm going to try to get some reproducible code and get back to you!

**Comment by buba447** [comment]
@kyle-fox The modal thing did the trick! I got a repo i think on my end. Digging into it.

**Comment by buba447** [comment]
@kyle-fox Got a possible fix here https://github.com/airbnb/lottie-ios/pull/815

Please pull and verify.

**Comment by kyle-fox** [comment]
@buba447 Fixed! Thank you 😄
