### ISSUE TITLE
Animations not working on mobile

### ISSUE THREAD

**Issue by SabrinaCurry** [airbnb/lottie-ios#89]
When I render out the animation with Bodymovin, it works fine on web but when placed in mobile elements start to get distorted or don't show at all. Any idea what may be the problem? Looked through the unsupported feature list and none of the unsupported features are being used in the animations so not too sure whats happening.
[lottie-issues.mov.zip](https://github.com/airbnb/lottie-ios/files/772256/lottie-issues.mov.zip)

**Comment by buba447** [comment]
I can't really tell anything from the video without knowing what the animation is suppose to look like. Would you mind sharing the after effects file? @SabrinaCurry

**Comment by buba447** [comment]
@SabrinaCurry I see the issue! Its a bug with out implementation of animating XY position as separate dimensions! Good catch! Thank you for letting us know!
I have fixed the issue here https://github.com/airbnb/lottie-ios/pull/90
It will be merged into master and available in the next cocoa pod release later this week :)
