### ISSUE TITLE
Support Alpha Inverted Mattes

### ISSUE THREAD

**Issue by rdd7** [airbnb/lottie-ios#93]
I use the four circle json files which are exported from bodymovin in my iOS  project，but the animation seems not correctly .
I'm not familiar with AE，but the exported json file works well in Android demo and http://svgsprite.com/demo/bm/player.php?render=canvas&bg=fff.

[Archive.zip](https://github.com/airbnb/lottie-ios/files/773357/Archive.zip)

**Comment by therealsalih** [comment]
Hi @rdd7 I took a look at your file and there are a few of things

in "circle01" we dont yet support Precomps or Time Remapping 

<img width="288" alt="screen shot 2017-02-14 at 9 05 12 am" src="https://cloud.githubusercontent.com/assets/5893643/22939837/d7ab13ea-f294-11e6-9945-2fd927e903be.png">

Also in "circle01"  "circle03" and "circle04" You're using Alpha Inverted mattes which we dont yet support. We only support regular Alpha mattes

<img width="442" alt="screen shot 2017-02-14 at 9 05 23 am" src="https://cloud.githubusercontent.com/assets/5893643/22939840/da2a552c-f294-11e6-933a-26c3e46ddb93.png">

We're working really hard to add these features and get parity between us and bodymovin, but it will take a little time

Follow this issue for precomps: https://github.com/airbnb/lottie-ios/issues/57
And I will turn THIS issue into one that tracks for Alpha Inverted mattes

You should be able to find some workarounds for now for these issues and still achieve your look.
Thanks @rdd7 !

**Comment by buba447** [comment]
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by johnkeese** [comment]
@buba447 I'm a little confused about support for Alpha Inverted Mattes.

It says it's unsupported in the [Readme](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features).

But says it's supported [here on airbnb.io](http://airbnb.io/lottie/after-effects/supported-features.html) and this task is marked as closed saying "Should be fixed in Lottie 2.0". 

Does the closing of this task mean it is now supported? Or is this still unsupported? Thanks!

**Comment by MartinBerthelsen** [comment]
@buba447 any news about @johnkeese question? 

Right now it seems unsupported on IOS, but works fine on Android(even though it says on [airbnb.io](http://airbnb.io/lottie/supported-features.html) that IOS has support for it too).
