### ISSUE TITLE
Issue using trim paths

### ISSUE THREAD

**Issue by Ushaka** [airbnb/lottie-ios#94]
Me again. This time I tried to use trim paths and shapes from Illustrator, which looks great through Bodymovin. Somehow parts of the animation does not follow through though. Any ideas?

Example: 
![lottieerror](https://cloud.githubusercontent.com/assets/2385335/22929378/b14ee114-f2bb-11e6-8378-d5c2c49a6233.gif)

File: https://www.dropbox.com/s/79yg7lldjct13ys/Play2Smile.aep?dl=0

**Comment by Ushaka** [comment]
So I figured out that Lottie did not support the offset value, but it worked when I rotated the element instead. That leaves only the position of the left eye, which is the exact same place and size of the right one in After Effects, but not in Lottie. Does Lottie calculate position/size differently or something?

**Comment by therealsalih** [comment]
I Ushaka! Are you using the latest version of Bodymovin AND the latest version of Lottie? My animation looks like this:

![feb-14-2017 08-36-28](https://cloud.githubusercontent.com/assets/5893643/22938498/c4e9c9c6-f290-11e6-8488-b50d224c68ad.gif)

So it looks like there is some difference in how the pause button is looking on iOS. Because here is what the same animation looks like in the android simulator

![feb-14-2017 08-51-23](https://cloud.githubusercontent.com/assets/5893643/22939210/d3c74854-f292-11e6-9685-6d63a2f80345.gif)

Looks like something with the trim paths. We'll try to figure this out

**Comment by therealsalih** [comment]
Hi Ushaka, here is a temporary workaround until we can figure out whats going on

<img width="351" alt="screen shot 2017-02-14 at 8 57 20 am" src="https://cloud.githubusercontent.com/assets/5893643/22939477/a6113720-f293-11e6-93af-af4c000d1d64.png">

I created two new layers for the pause button where I took Trim Paths off. Check it out in this AE file:
[Play2Smile.aep.zip](https://github.com/airbnb/lottie-ios/files/774771/Play2Smile.aep.zip)

**Comment by buba447** [comment]
@Ushaka Fixed it! Heres the PR https://github.com/airbnb/lottie-ios/pull/99

Its been merged into master and will be available with the next dot release of Carthage or Cocoapods next week. For now you can just pull master though :)
