### ISSUE TITLE
Dotted line appears at the wrong time in app

### ISSUE THREAD

**Issue by Bigbigann** [airbnb/lottie-ios#965]
## This issue is a:
- Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 
- iOS

## What Language are you in?
- Swift

## Expected Behavior 

![image](https://user-images.githubusercontent.com/48397314/60404009-60382e00-9bf8-11e9-813e-a5f3f1030201.png)

## Actual Behavior

The line goes above the plane when viewing it from the actual app. However, when previewing on web and on Lottie app, there is no such issue.

![image](https://user-images.githubusercontent.com/48397314/60404019-7645ee80-9bf8-11e9-8ac6-b7787fb1871d.png)

## Animation JSON
[unabletoload_flyout.json.zip](https://github.com/airbnb/lottie-ios/files/3343505/unabletoload_flyout.json.zip)

THANKS IN ADVANCE!

**Comment by buba447** [comment]
Im not certain but I think this may be related to https://github.com/airbnb/lottie-ios/issues/976.
Can you tell me if the animation is using any ease keyframes?

**Comment by Bigbigann** [comment]
thanks @buba447 
yea i am using ease keyframes for the line and plane as well would this cause trouble?
here is the screenshot of the keyframe for the line movement
![image](https://user-images.githubusercontent.com/48397314/61100923-12ef7280-a4bc-11e9-8adf-5b6b6d0aabaf.png)
![image](https://user-images.githubusercontent.com/48397314/61100930-18e55380-a4bc-11e9-960e-3d8151d8175f.png)

**Comment by calda** [comment]
This appears to be fixed in the new Core Animation rendering engine we added recently, as of #1714:

| Main thread engine | Core Animation engine |
| ---- | ---- |
| ![Simulator Screen Shot - iPhone 8 - 2022-08-10 at 11 48 27](https://user-images.githubusercontent.com/1811727/184003494-b56bee53-2069-4ff3-8acf-26a0c62115c4.png) | ![Simulator Screen Shot - iPhone 8 - 2022-08-10 at 11 48 18](https://user-images.githubusercontent.com/1811727/184003505-e963bfd2-7a0b-4172-8c0c-50532ad032b3.png) |
